version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: [
        "./wait-for-it.sh", "db:5432", "-t", "30", "--",
        "python", "src/manage.py", "runserver", "0.0.0.0:8000"
    ]
    ports:
      - 8080:8000
    env_file:
      - .env

  db:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=manatal_user
      - POSTGRES_PASSWORD=helloworld
      - POSTGRES_DB=manatal
    ports:
      - 5434:5432
