# Generated by Django 3.2.9 on 2021-11-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'schools',
            },
        ),
    ]
